[package]
name = "molfi"
version = "1.0.0"
edition = "2024_07"

[dependencies]
starknet = "2.15.1"

[dev-dependencies]
snforge_std = "0.56.0"
assert_macros = "2.15.1"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
