//! Cairo side of the parity harness.
//!
//! These vectors are generated by `packages/sdk/test/parity.ts` from the TypeScript kernel and
//! pasted here. Both implementations run the same inputs and must agree exactly — not close,
//! exactly, because a one-unit divergence from truncating division is precisely the kind of
//! disagreement nobody notices until a settlement is contested.
//!
//! Regenerate with: `pnpm --filter @molfi/sdk parity`

use molfi::pricing::{half_prob, normal_table, payout_for, prob_inside, quote, sqrt_u256};

/// (input, expected) pairs for sqrt, from the kernel's Babylonian loop.
///
/// Note `sqrt(2) = 2`, which is not the floor of the real root. The Babylonian seed makes
/// both implementations stop a step early for inputs that small, and parity means matching
/// what the kernel does rather than what a textbook does. It never bites in practice: sqrt is
/// only ever called on `(blocks * 1e8) / ref_blocks`, which is at least 1e8.
#[test]
fn sqrt_agrees_with_the_kernel() {
    let cases = array![
        (0_u256, 0_u256), (1, 1), (2, 2), (3, 1), (4, 2), (8, 2), (9, 3), (15, 3), (16, 4),
        (99, 9), (100, 10), (10_001, 100), (1_000_000, 1_000), (100_000_000, 10_000),
        (123_456_789, 11_111), (999_999_999_999, 999_999),
    ];
    let mut i = 0;
    loop {
        if i == cases.len() {
            break;
        }
        let (input, expected) = *cases.at(i);
        assert(sqrt_u256(input) == expected, 'sqrt parity');
        i += 1;
    };
}

#[test]
fn half_prob_agrees_with_the_kernel() {
    let t = normal_table();
    let cases = array![
        (0_u256, 0_u256), (2_500, 197_413), (5_000, 382_925), (3_750, 290_169),
        (10_000, 682_689), (20_000, 954_500), (39_999, 999_936), (40_000, 999_937),
        (100_000, 999_937),
    ];
    let mut i = 0;
    loop {
        if i == cases.len() {
            break;
        }
        let (z, expected) = *cases.at(i);
        assert(half_prob(t, z) == expected, 'half_prob parity');
        i += 1;
    };
}

#[test]
fn prob_inside_agrees_with_the_kernel() {
    let t = normal_table();
    // (spot, low, high, sigma, expected prob in 1e6)
    let cases = array![
        (100_000_u256, 99_000_u256, 101_000_u256, 500_000_u256, 954_500_u256),
        (100_000, 95_000, 105_000, 500_000, 999_937),
        (100_000, 90_000, 110_000, 500_000, 999_937),
        (50_000, 49_500, 50_500, 250_000, 999_937),
    ];
    let mut i = 0;
    loop {
        if i == cases.len() {
            break;
        }
        let (spot, low, high, sigma, expected) = *cases.at(i);
        assert(prob_inside(t, spot, low, high, sigma) == expected, 'prob parity');
        i += 1;
    };
}

#[test]
fn quote_agrees_with_the_kernel() {
    let t = normal_table();
    let cases = array![
        (100_000_u256, 99_000_u256, 101_000_u256, 500_000_u256, 300_u256, 10_161_u256),
        (100_000, 95_000, 105_000, 500_000, 300, 9_700),
        (100_000, 90_000, 110_000, 500_000, 0, 10_000),
    ];
    let mut i = 0;
    loop {
        if i == cases.len() {
            break;
        }
        let (spot, low, high, sigma, edge, expected) = *cases.at(i);
        let q = quote(t, spot, low, high, sigma, edge);
        assert(q.multiplier_bps == expected, 'quote parity');
        i += 1;
    };
}

#[test]
fn payout_agrees_with_the_kernel() {
    let cases = array![
        (1_000_u256, 20_000_u256, 2_000_u256), (1_000, 10_000, 1_000), (3, 15_000, 4),
        (7, 33_333, 23), (1_000_000, 623_393, 62_339_300),
    ];
    let mut i = 0;
    loop {
        if i == cases.len() {
            break;
        }
        let (stake, mult, expected) = *cases.at(i);
        assert(payout_for(stake, mult) == expected, 'payout parity');
        i += 1;
    };
}
